#!/bin/bash

set -ex

FSGROUP=$(oc get dc $1 -o jsonpath='{.spec.template.spec.containers[0].securityContext.fsGroup}')

if [[ "${FSGROUP}" ]]; then
  oc patch dc $1 --type json -p '[
    { "op": "add", "path": "/spec/template/spec/securityContext/runAsUser", "value": 0 },
    { "op": "remove", "path": "/spec/template/spec/containers/0/securityContext/fsGroup" },
    { "op": "add", "path": "/spec/template/spec/volumes/0/secret/defaultMode", "value": 256 },
    { "op": "add", "path": "/spec/template/spec/volumes/1/configMap/defaultMode", "value": 420 }
  ]'
else
  oc patch dc $1 --type json -p '[
    { "op": "add", "path": "/spec/template/spec/securityContext/runAsUser", "value": 0 },
    { "op": "add", "path": "/spec/template/spec/volumes/0/secret/defaultMode", "value": 256 },
    { "op": "add", "path": "/spec/template/spec/volumes/1/configMap/defaultMode", "value": 420 }
  ]'
fi
