apiVersion: v1
kind: List
items:
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: tester
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: linux-system-roles
    spec:
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: docker.io/linuxsystemroles/test-harness
        - name: staging
          from:
            kind: DockerImage
            name: docker.io/linuxsystemroles/test-harness:staging
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: linux-system-roles
    spec:
      replicas: 1
      selector:
        name: linux-system-roles
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - linux-system-roles
            from:
              kind: ImageStreamTag
              name: linux-system-roles:latest
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            name: linux-system-roles
        spec:
          serviceAccountName: tester
          restartPolicy: Always
          containers:
            - name: linux-system-roles
              image: docker.io/linuxsystemroles/test-harness
              volumeMounts:
                - name: secrets
                  mountPath: /secrets
                  readOnly: true
                - name: config
                  mountPath: /config
                  readOnly: true
                - name: cache
                  mountPath: /cache
              securityContext:
                privileged: true
                fsGroup: 1000
          volumes:
            - name: secrets
              secret:
                secretName: secrets
            - name: config
              configMap:
                name: config
            - name: cache
              emptyDir:
