---
- name: Generate secrets file
  shell: oc -n {{ test_harness_namespace }} create secret generic {{ __test_harness_secret_name }} \
    --from-file=github-token={{ test_harness_secrets_dir }}/{{ __test_harness_ghtoken_file }} \
    --from-file=id_rsa={{ test_harness_secrets_dir }}/id_rsa \
    --from-file=known_hosts={{ test_harness_secrets_dir }}/known_hosts \
    --from-file=openstack-psi={{ test_harness_secrets_dir }}/openstack-psi \
    --from-file=system-roles-os={{ test_harness_secrets_dir }}/system-roles-os \
    --dry-run=true \
    --output=yaml > {{ __test_harness_secret_name }}.yml
  changed_when: false

- name: Ensure secrets are present
  k8s:
    src: "{{ __test_harness_secret_name }}.yml"
    namespace: "{{ test_harness_namespace }}"
    state: present
  when: not test_harness_dry_run

- name: Remove secrets file
  file:
    state: absent
    path: "{{ __test_harness_secret_name }}.yml"
  changed_when: false
  when: not test_harness_dry_run
