---
- name: Create temp file for secrets
  tempfile:
    state: file
    suffix: lsr.yml
  register: secrets_tempfile
  changed_when: false

- name: Generate secrets file
  shell: oc -n {{ test_harness_namespace }} create secret generic secrets \
    --from-file={{ test_harness_secrets_dir }} --dry-run=true \
    --output=yaml > {{ secrets_tempfile.path }}
  changed_when: false

- name: Ensure secrets are present
  k8s:
    src: "{{ secrets_tempfile.path }}"
    namespace: "{{ test_harness_namespace }}"
    state: present

- name: Remove secrets file
  file:
    state: absent
    path: "{{ secrets_tempfile.path }}"
  changed_when: false
