---
- name: Generate config file
  shell: oc -n {{ test_harness_namespace }} create configmap {{ __test_harness_cm_name }} \
    --from-file=config.json={{ test_harness_config_dir }}/{{ __test_harness_cm_file }} --dry-run=true \
    --output=yaml > {{ __test_harness_cm_name }}.yml
  changed_when: false

- name: Ensure configmap is present
  k8s:
    src: "{{ __test_harness_cm_name }}.yml"
    namespace: "{{ test_harness_namespace }}"
    state: present
    apply: true
  when: not test_harness_dry_run

- name: Remove config file
  file:
    state: absent
    path: "{{ __test_harness_cm_name }}.yml"
  changed_when: false
  when: not test_harness_dry_run
