---
- name: Ensure {{ __test_harness_environ }} configmap is present
  include_tasks: create-configmap.yml

- name: create the openshift objects file from the template
  template:
    src: "{{ test_harness_openshift_template }}"
    dest: "{{ __test_harness_dc }}.yml"
  changed_when: false

- name: Block for tasks that only run when not using test_harness_dry_run
  when: not test_harness_dry_run
  block:
    # NOTE: This is not idempotent - it will report changed every time
    # seems to be a problem in the k8s module
    - name: Ensure {{ __test_harness_environ }} objects are present
      k8s:
        src: "{{ __test_harness_dc }}.yml"
        namespace: "{{ test_harness_namespace }}"
        state: present

    - name: Initiate build of {{ __test_harness_environ }} image
      command: oc -n {{ test_harness_namespace }} start-build --follow {{ __test_harness_bc }}
      changed_when: false

    - name: Get {{ __test_harness_environ }} dc rollout status
      command: oc -n {{ test_harness_namespace }} rollout status --watch=false dc/{{ __test_harness_dc }}
      register: register_dc_rollout
      changed_when: false

    - name: Ensure latest {{ __test_harness_environ }} dc is rolled out
      command: oc -n {{ test_harness_namespace }} rollout latest dc/{{ __test_harness_dc }}
      when: register_dc_rollout.stdout is match("^replication controller.*successfully rolled out$")
      changed_when: false
